### ISSUE TITLE
Precise control of sliders

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-quadratics#73] opened 2018-10-18 22:49 UTC
**Test device:**
Dell Laptop and iPad Air 2
**Operating System:**
Win 10 and iOS 12
**Browser:**
Chrome and Safari
**Problem description:**
For https://github.com/phetsims/QA/issues/211
The sliders that controls the "a" variable slider on the explore screen has an odd jump in size between points on the slider.  This means it can be impossible to set the variable on a desired number, such as 2.00.  You can get close, but not land on it.  The steps also seem to vary by device.  On Windows 10 the slider moves between 1.98 and 2.02.  On iOS 12 it jumps between 1.90 and 2.05.
**Steps to reproduce:**
1. Go to the Explore screen
2. Manipulate the "a" slider to try to land on various whole numbers
3. Manipulate the other two sliders on the screen to compare.  These do not seem to miss numbers

Troubleshooting information (do not edit):

<details>

Name: ‪Graphing Quadratics‬
URL: https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.38/phet/graphing-quadratics_en_phet.html
Version: 1.0.0-dev.38 2018-10-18 21:15:53 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"644353d6","branch":"master"},"brand":{"sha":"1fd6682e","branch":"master"},"chipper":{"sha":"fc5919bb","branch":"master"},"dot":{"sha":"dcccfddd","branch":"master"},"graphing-lines":{"sha":"08b2b43e","branch":"master"},"graphing-quadratics":{"sha":"9b807638","branch":"master"},"joist":{"sha":"b12072c7","branch":"master"},"kite":{"sha":"380cef53","branch":"master"},"phet-core":{"sha":"269c4c8a","branch":"master"},"phet-io":{"sha":"ce77e241","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"534dc595","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"3372700d","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"09507f4d","branch":"master"},"phet-io-wrappers":{"sha":"0a4a3153","branch":"master"},"phetcommon":{"sha":"a2a1aaba","branch":"master"},"query-string-machine":{"sha":"9ae63aab","branch":"master"},"scenery":{"sha":"d7e6c53e","branch":"master"},"scenery-phet":{"sha":"344597e6","branch":"master"},"sherpa":{"sha":"0989d371","branch":"master"},"sun":{"sha":"289fce23","branch":"master"},"tambo":{"sha":"fe63321c","branch":"master"},"tandem":{"sha":"2c4b970a","branch":"master"}}

</details>

**Comment by pixelzoom** [comment] 2018-10-18 23:16
This is currently working as designed, but deserves some explanation.

The "a" slider purposely has a quadratic response to it.  (All of the other sliders are linear.) And being able to set it to specific values is not a goal.  For all sliders, setting to specific values would only be possible if we  added tweaks to the ends of the sliders.  The steps are going to vary by screen resolution - how many pixels there are in the slider determines how those pixels get mapped to values.

@amanda-phet please review, let me know if you want to make any changes.   If no changes are needed, feel free to close.

**Comment by pixelzoom** [comment] 2018-10-18 23:17
Also removing the "bug" label and relabeling with "design".

**Comment by pixelzoom** [comment] 2018-10-18 23:44
To clarify why the "a" slider has a quadratic response... It's adjusting the coefficient of the quadrstic term _ax<sup>2</sup>_ of the quadratic equation. If the slider was linear, it would not provide a smooth change in the shape of the parabola, which is what is desired.

**Comment by pixelzoom** [comment] 2018-10-19 16:16
Here's an example of a quiz that would be impossible to solve, since it involves specific values:

On the _Focus & Directrix_ screen, where is the focus located when p=3, h=2, k=1 ?

While it may be possible to set sliders to those specific values on some platforms, it's unlikely to be possible on all platforms.  And it's certainly not possible for all values of p, h, k.

**Comment by pixelzoom** [comment] 2018-10-19 16:18
Here's an example of a problematic quiz:

On the _Focus & Directrix_ screen, where is the focus located when p=3, h=2, k=1 ?

While it may be possible to set sliders to those specific values on some platforms, it's unlikely to be possible on all platforms.  And it's certainly not possible for all values of p, h, k.   So even if you solve the problem in your head, you can't confirm by looking at a focus point on the graph.

**Comment by amanda-phet** [comment] 2018-10-23 16:22
If someone is designing a PhET-iO wrapper, can the values at least be set by specifying the starting state? 

In general, I don't have a problem with the inability to set precise values because that is not part of the learning goals. However, if this is an issue for PhET-iO perhaps we need to discuss with @ariel-phet and @kathy-phet . I don't think this PhET sim is the right tool for helping to answer quiz questions about parabolas, so I'm inclined to leave this as-is, but again since I'm not too experienced with PhET-iO I would like to consult with Ariel and Kathy.

**Comment by pixelzoom** [comment] 2018-10-23 16:39
> If someone is designing a PhET-iO wrapper, can the values at least be set by specifying the starting state?

Yes. Precise values can be specified via PhET-iO.

>  ... I would like to consult with Ariel and Kathy.

Keep me posted.

**Comment by pixelzoom** [comment] 2018-10-24 01:32
@amanda-phet @ariel-phet I realize that being able to set precise values is not part of the learning goals, and that the basic concepts are qualitative.  But any time that you have a quantitative control, I think there's an expectation that you can set it to specific values.  That was certainly the expectation of the QA team during testing, and I think it will be an expectation of students and educators.

**Comment by kathy-phet** [comment] 2018-10-24 05:12
Making these snappy sliders would be one way to make this reproducible values across platforms. 0.5 jumps would work on most sliders and give you about 24 landing points or more, and then “a” slider would need more specialty jumps.

Sent from my iPhone

On Oct 23, 2018, at 7:32 PM, Chris Malley <notifications@github.com<mailto:notifications@github.com>> wrote:


@amanda-phet<https://github.com/amanda-phet> @ariel-phet<https://github.com/ariel-phet> I realize that being able to set precise values is not part of the learning goals, and that the basic concepts are qualitative. But any time that you have a quantitative control, I think there's an expectation that you can set it to specific values. That was certainly the expectation of the QA team during testing, and I think it will be an expectation of students and educators.

**Comment by pixelzoom** [comment] 2018-10-24 18:02
FYI all of the sliders currently are "snappy sliders". The snap intervals is 0.1, except for "a" which is 0.01. The problem is that with these intervals, the slider track is not long enough to represent all values. "Specialty jumps" for "a" will be difficult and potentially confusing, due to its quadratic taper.

**Comment by kathy-phet** [comment] 2018-10-24 22:53
Right now, most of the sliders display with only one decimal, so they hit every value that can (2.0, 2.1) pretty much. I was thinking if they when (2.0, 2.5, 3.0) then they would be long enough pixel wise that they could reliability be snapped to a reproducible value but would still feel pretty smooth since they would have at least 25 landing points over their length. 

For "a", I would recommend snapping by 0.5 between 1-6, then snapping to 0.75, 0.5, 0.4, 0.3,, 0.2, 0.15, 0.1, 0.05, 0, .... suggestion based off what is possible with the sim right now in terms of slider length. Or could do 0.9, 0.8, 0.7, 0.6 too.

**Comment by pixelzoom** [comment] 2018-10-25 01:50
> Right now, most of the sliders display with only one decimal, so they hit every value that can (2.0, 2.1) pretty much. 

That's not the case.  It varies by platform and by screen resolution. For example, on Chrome I can't reliably set most sliders to 0.1.

**Comment by pixelzoom** [comment] 2018-10-25 14:15
To evaluate @kathy-phet's proposal https://github.com/phetsims/graphing-quadratics/issues/73#issuecomment-432855419, see [1.0.0-dev.41](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.41/phet/graphing-quadratics_en_phet.html).  Linear sliders (b,c,p,h,k) snap to 0.5 increments. The "a" slider is unchanged; implementing that proposal will be a mini-project. 

Compared to the 0.1 increment in [1.0.0-dev.40](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.40/phet/graphing-quadratics_en_phet.html), this of course looks and feels much less smooth, a bit jerky even. Is this really the direction that we want to move to address this issue?

Also worth noting... Using a slider snap interval that is larger than the number of decimal places that the slider can display starts to make these sliders operate less like continuous controls.  That would seem to suggest using pickers in all screen -- not something I'm recommending, just noting that our sliders are starting to be less continuous.

**Comment by kathy-phet** [comment] 2018-10-25 14:32
Amanda and I can discuss today. Thanks for creating this test.

Sent from my iPhone

On Oct 25, 2018, at 8:15 AM, Chris Malley <notifications@github.com<mailto:notifications@github.com>> wrote:


To evaluate @kathy-phet<https://github.com/kathy-phet>'s proposal #73 (comment)<https://github.com/phetsims/graphing-quadratics/issues/73#issuecomment-432855419>, see 1.0.0-dev.41<https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.41/phet/graphing-quadratics_en_phet.html>. Linear sliders (b,c,p,h,k) snap to 0.5 increments. The "a" slider is unchanged; implementing that proposal will be a mini-project.

Compared to the 0.1 increment in 1.0.0-dev.40<https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.40/phet/graphing-quadratics_en_phet.html>, this of course looks and feels much less smooth, a bit jerky even. Is this really the direction that we want to move to address this issue?

Also worth noting... Using a slider snap interval that is larger than the number of decimal places that the slider can display starts to make these sliders operate less like continuous controls. That would seem to suggest using pickers in all screen -- not something I'm recommending, just noting that our sliders are starting to be less continuous.

**Comment by amanda-phet** [comment] 2018-10-25 20:22
After much discussion, we decided to leave the sliders as they are in dev.40. I believe that if a teacher wants all students looking at the same parabola, they can use the Standard Form screen (as opposed to Explore). In the Focus & Directrix screen I much prefer the p slider to have increments of 0.1 and not 0.5, and for h and k the user can always drag the vertex to integer coordinates. 

Assigning to @pixelzoom to revert changes.

**Comment by pixelzoom** [comment] 2018-10-26 02:00
Changes were never permanent, so there's nothing to revert.  Closing.

**Closed by pixelzoom** 2018-10-26 02:00 UTC
Labels: design:general
