### ISSUE TITLE
Problem with Point Tool background color.

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/graphing-quadratics#170] opened 2021-08-27 18:11 UTC
I can tell the point tool is "on" the curve because it feels attached. When I try to drag it away, it doesn't move until I drag quite a bit. So even though the point tool is on the curve, the background is white instead of the color of the curve. I get to this point by dragging the tool along the curve, but right at the vertex the background color changed. 

![image](https://user-images.githubusercontent.com/7852916/131170401-694159b0-d2be-4dba-929a-4c06f6bc1dd1.png)

I can reproduce this using other curves, and I'm not sure if there is a pattern yet to when this happens and when it doesn't. 

I consistently get this behavior with 

y = -6x^2 + 6x
y = 6x^2 - 6x + 3
y = 6x^2 + 6x
y = 6x^2 + 3x

but not with 
y=2x^2 - 6x + 3 

It's tricky to get curves with values for a that aren't decimals, so a=6 is the easiest for me to test.

**Comment by pixelzoom** [comment] 2021-08-29 00:07
@amanda-phet @Nancy-Salpepi @KatieWoe please provide information on what type of device (mouse or touch) you're using for the tests you've reported above.  It would also be helpful to know if you can reproduce the same behavior on mouse and touch devices.

**Comment by pixelzoom** [comment] 2021-08-29 00:21
I took a quick look at this.  

Relevant code in `PointTool` (model), the quadratic that the point tool is on is derived:

```js
this.quadraticProperty = new DerivedProperty(
      [ this.positionProperty, quadraticsProperty ],
      ( position, quadratics ) => {
        if ( graph.contains( position ) ) {
          return this.getQuadraticNear( position,
            GQQueryParameters.pointToolThreshold, GQQueryParameters.pointToolThreshold );
        }
        else {
          return null;
        }
      }
```

In PointToolNode (view), there's a listener that observes the model and changes the tool's background color:

```js
        // update colors
        if ( graph.contains( position ) && onQuadratic && graphContentsVisible ) {

          // color code the display to onQuadratic
          coordinatesNode.foreground = options.foregroundHighlightColor;
          backgroundNode.fill = onQuadratic.color;
        }
        else {
          coordinatesNode.foreground = options.foregroundNormalColor;
          backgroundNode.fill = options.backgroundNormalColor;
        }
```

In `PointToolDragListener` (view) we snap to the curve:

```js
          // If we're close enough to a quadratic, snap to that quadratic.
          const snapQuadratic = pointTool.getQuadraticNear( position,
            GQQueryParameters.snapOffDistance, GQQueryParameters.snapOnDistance );
          if ( snapQuadratic ) {

            // Get the closest point that is on the quadratic.
            position = snapQuadratic.getClosestPoint( position );

            // We will be snapping the x value as it will be displayed by the point tool.
            // See See https://github.com/phetsims/graphing-quadratics/issues/169.
            let x = Utils.toFixedNumber( position.x, GQConstants.POINT_TOOL_DECIMALS );

            // If x is close to an integer value, snap to that integer value.
            // See https://github.com/phetsims/graphing-quadratics/issues/169.
            const closestInteger = Utils.toFixedNumber( x, 0 );
            if ( Math.abs( x - closestInteger ) < xSnapTolerance ) {
              x = closestInteger;
            }

            const y = snapQuadratic.solveY( x );
            position = new Vector2( x, y );
          }
```

The model and view are both calling `getQuadraticNear`.  The problem (I believe) is that after the view calls `getQuadraticNear`, it modifies the x and y coordinates to "snap".  So by the time we set `pointTool.positionProperty`, the modified point may no longer be on the quadratic, as determined by the model when it calls `getQuadraticNear`.

**Comment by Nancy-Salpepi** [comment] 2021-08-30 12:57
I was using a trackpad initially on my MacBook air when I was able to change the background color of the vertex. I can reproduce the same results with a mouse. I was able to do this on the published sim as well as 1.1.0-rc.1 and 1.2.0-rc.1.

**Comment by KatieWoe** [comment] 2021-08-30 14:46
I was on Win 10 Chrome with a trackpad

**Comment by pixelzoom** [comment] 2021-08-30 16:51
@amanda-phet and I discussed this via Zoom.  Since this a problem in the published version, and the priority for 1.2 is PhET-iO support (I think?), then I'm tempted to defer this until a future release.  But neither of us are clear on priorities for this release, we've gone far down the "improve the point tool" path, and this problem seems to be more pronounced because of that.  So we both would like to fix this for 1.2.   So I'll continue to work on this.

**Comment by pixelzoom** [comment] 2021-08-30 19:25
I have a new theory about the cause of this problem.  There appears to be a problem with Quadratic `getClosestPoint`, the method that gets the point on a curve that is closest to a specified point.  If I print the results of this method to the console, here's what I see near the vertex, whenever the background color of the point tool is incorrect:

> closestPoint=Vector2(NaN, NaN)

`getClosestPoint` starts by getting the roots, by calling `Utils.solveCubicRootsReal`.  And that method is returning values that are not finite, verified by adding this assertion (which fails):

`    assert && assert( _.every( roots, root => isFinite( root ) ) );`

**Comment by pixelzoom** [comment] 2021-08-30 19:45
Adding this to the end of Quadratic `getClosestPoint`:

```js
    if ( !closestPoint.isFinite() ) {
      console.log( '-----------------------' );
      console.log( `closestPoint=${closestPoint}` );
      console.log( `roots=${roots.toString()}` );
      console.log( `a=${x0} y0=${y0} a=${this.a} b=${this.b} c=${this.c}` );
      console.log( `Utils.solveCubicRootsReal args: ${2 * a * a} ${3 * a * b} ${b * b + 2 * a * c - 2 * a * y0 + 1} ${b * c - b * y0 - x0}` );
    }
```

For y = -6x^2 + 6x + 0, I see console output like this when dragging the point too around the vertex of the curve:

```
-----------------------
closestPoint=Vector2(NaN, NaN)
Quadratic.js:357 roots=NaN,NaN,NaN
Quadratic.js:358 a=0.5 y0=1.5 a=-6 b=6 c=0
Quadratic.js:359 Utils.solveCubicRootsReal args: 72 -108 55 -9.5
```

Confirming by calling `Utils.solveCubicRootsReal` directly in the console:

```
> phet.dot.Utils.solveCubicRootsReal( 72, -108, 55, -9.5 )
(3) [NaN, NaN, NaN]
```

The documentation for `Utils.solveCubicRootsReal ` says:

```js
   * @returns {Array.<number>|null} - The real roots of the equation, or null if all values are roots. If the root has
   *                                  a multiplicity larger than 1, it will be repeated that many times.
   *
```

While `NaN` is indeed a `{number}`, I doubt that it's considered a "real root".   So I suspect that `Utils.solveCubicRootsReal` is buggy.  I'll need @jonathanolson's assistance with this.

**Comment by pixelzoom** [comment] 2021-08-30 19:59
I added a break point to `Utils.solveCubicRootsReal`.  Then typed this into the browser console:

> phet.dot.Utils.solveCubicRootsReal( 72, -108, 55, -9.5 )

Stepping through the code, the problem looks like it's in these lines:

```js
473 // all unique
474 let qX = -q * q * q;
475 qX = Math.acos( r / Math.sqrt( qX ) );
476 const rr = 2 * Math.sqrt( -q );
```

For Line 474, `qX = -9.922903012752013e-8`, `q = 0.004629629629629613`
For Line 475 `qX = NaN`, `r = 0`
For Line 476, `rr = NaN`, `q = 0.004629629629629613`

**Comment by pixelzoom** [comment] 2021-08-30 20:05
This is as far as I can take this. I'll need @jonathanolson's assistance.

**Comment by jonathanolson** [comment] 2021-08-30 20:47
It looks like this is definitely a single-real-root scenario (roots are 0.5 - 0.117851i, 0.5 + 0.117851i, 0.5). The discriminant was barely above the `1e-7` threshold. It looks like the best option is to increase the threshold, since we've seen a case where numerical imprecision will trigger the wrong case.

**Comment by jonathanolson** [comment] 2021-08-30 20:47
Committed a hopeful fix above, can you verify?

**Comment by pixelzoom** [comment] 2021-08-30 20:58
Testing with  y = -6x<sup>2</sup> + 6x + 0 in the _Explore_ screen ...

It's even worse now. It returning `[NaN, NaN, NaN]` more often near the vertex, and failing for points that are not at the vertex. For example:

```
closestPoint=Vector2(NaN, NaN)
Quadratic.js:358 roots=NaN,NaN,NaN
Quadratic.js:359 x0=0.5733964870309585 y0=1.4660832405076079 a=-6 b=6 c=0
Quadratic.js:360 Utils.solveCubicRootsReal args: 72, -108, 54.592998886091294, -9.369895930076606
```

**Comment by pixelzoom** [comment] 2021-08-30 21:07
@jonathanolson fixed his fix in the above commit, and it's bettter.  But it's still failing, for example:

```
> phet.dot.Utils.solveCubicRootsReal( 72, -108, 54.309261152632615, -9.157483833649408 )
[ NaN, NaN, NaN ]
```

**Comment by pixelzoom** [comment] 2021-08-30 21:44
If I decrease the discriminate threshold further in `Utils.solveCubicRootsReal`, from 1e-8 to 1e-9, the problem appears to go away.  Changing this threshold (as has already been done in https://github.com/phetsims/dot/commit/272fb9f54a8365317739f3d11e72c1f7f374b359) is a concern because it could break other sims.  How about if we revert to the original threshold of 1e-7, and add an optional parameter that sims can use to specify a different threshold?  The function signature would be:

```js
solveCubicRootsReal( a, b, c, d, discriminateThreshold = 1e-7 )
```

**Comment by pixelzoom** [comment] 2021-08-30 21:57
Suggested patch:

```js
Index: js/Utils.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/Utils.js b/js/Utils.js
--- a/js/Utils.js	(revision 272fb9f54a8365317739f3d11e72c1f7f374b359)
+++ b/js/Utils.js	(date 1630360627590)
@@ -425,10 +425,11 @@
    * @param {number} b
    * @param {number} c
    * @param {number} d
+   * @param {number} [discriminantThreshold] - for determining whether we have a single real root
    * @returns {Array.<number>|null} - The real roots of the equation, or null if all values are roots. If the root has
    *                                  a multiplicity larger than 1, it will be repeated that many times.
    */
-  solveCubicRootsReal( a, b, c, d ) {
+  solveCubicRootsReal( a, b, c, d, discriminantThreshold = 1e-7 ) {
     // TODO: a Complex type!
 
     // Check for a degenerate case where we don't have a cubic
@@ -455,7 +456,7 @@
     const discriminant = q * q * q + r * r;
     const b3 = b / 3;
 
-    if ( discriminant > 1e-8 ) {
+    if ( discriminant > discriminantThreshold ) {
       // a single real root
       const dsqrt = Math.sqrt( discriminant );
       return [ Utils.cubeRoot( r + dsqrt ) + Utils.cubeRoot( r - dsqrt ) - b3 ];
```

**Comment by jonathanolson** [comment] 2021-08-30 23:16
Handled above, and integrated assertions to every single type of way roots could be returned. Aqua fuzz passed. @pixelzoom can you verify?

**Comment by pixelzoom** [comment] 2021-08-30 23:58
Thanks @jonathanolson, verified in master.

I change graphing-quadratics Quadratic.js to use `discriminantThreshold = 1e-9`.   

Patched the 1.2 release like this:

```
% grunt checkout-target --repo=graphing-quadratics --target=1.2
% cd graphing-quadratics
% git cherry-pick 5daae58dfc24d71ecca15a39096f90e14f0da8cd
% cd dot
% git checkout -b graphing-quadratics-1.2
% git cherry-pick 6ac2f0579fb330e15f959d1ecece4a937f9e4941
% git cherry-pick 272fb9f54a8365317739f3d11e72c1f7f374b359
% git cherry-pick f291f519cb6c5919e1152dd83b9d4c7e1674eaee
% cd graphing-quadratics
% grunt --brands=phet
// test
% cp build/phet/dependencies.json .
% git add dependencies.json 
% git commit -m 'patch for https://github.com/phetsims/graphing-quadratics/issues/170'
% git push origin 1.2
% cd dot
% git push origin graphing-quadratics-1.2
```

**Comment by pixelzoom** [comment] 2021-08-31 00:06
@amanda-phet please review in master before I create the next RC.  Take a close look at the point tool behavior of course. But also please look at the Point On Parobola manipulator - it uses the same code as point tool to keep the point on the curve.

**Comment by amanda-phet** [comment] 2021-08-31 15:46
The point tool seems to be working great. Is there something specific to test for the point on parabola manipulator? The point is staying attached to the curve just fine with various curves, and the coordinates are accurate. Let me know if there's anything else to verify for that, but I think it all looks good! 

Thanks for hunting down the source of the problem.

**Comment by pixelzoom** [comment] 2021-08-31 16:33
Thanks @amanda-phet. Nothing specific to test for Point On Parabola, just that it remains attached to the curve.

**Comment by pixelzoom** [comment] 2021-08-31 16:51
This issue is fixed and ready for testing in the next RC.

**Comment by KatieWoe** [comment] 2021-08-31 19:43
This looks ok in rc.3. Will reopen if something comes up.

**Closed by KatieWoe** 2021-08-31 19:43 UTC
Labels: type:bug, status:ready-for-qa
