### ISSUE TITLE
Consider dilating pointer areas for checkboxes

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/graphing-quadratics#197] opened 2023-06-28 14:21 UTC
**Test device**
MacBook Air M1 chip

**Operating System**
13.4

**Browser**
Safari 16.5

**Problem description**
For https://github.com/phetsims/qa/issues/959, I see the same thing that I reported in https://github.com/phetsims/molecule-polarity/issues/161. On all screens, the touch/pointer areas for checkboxes are not flush against each other. 

**Visuals**
<img width="210" alt="Screenshot 2023-06-28 at 10 16 52 AM" src="https://github.com/phetsims/graphing-quadratics/assets/87318828/f02bddad-38d3-4c6a-9908-2fcea7d21892">

**Comment by zepumph** [comment] 2023-06-28 15:40
@arouinfar can you comment on this? Don't we have a stand for extending them to the edge of the panel?

**Comment by arouinfar** [comment] 2023-06-28 17:37
The pointerAreas usually have the same width, extending to the end of largest Node in the group. For example:
<img width="355" alt="image" src="https://github.com/phetsims/graphing-quadratics/assets/8419308/7f67b780-8156-4f83-857d-e4facdc51177">

Here, I would dilate things a bit vertically, and match the width of the longest checkbox title.

**Comment by pixelzoom** [comment] 2023-07-02 02:39
> @arouinfar can you comment on this? Don't we have a stand for extending them to the edge of the panel?

This happens to be a "standard" that I don't at all agree with.  It works great on a device like an phone or tablet. It's not at all appropriate imo for a general web application.   

It's also burdensome when it's not possible to use VerticalCheckboxGroup -- like in this example, where there's a separator.

But I'll do it rather than debate it again.

**Comment by pixelzoom** [comment] 2023-07-02 02:40
@zepumph said:
> @arouinfar can you comment on this? Don't we have a stand for extending them to the edge of the panel?

Assuming you mean "standard"...  This happens to be a standard that I don't at all agree with.  It works great on a device like an phone or tablet. It's not at all appropriate imo for a general web application.   

It's also burdensome when it's not possible to use VerticalCheckboxGroup -- like in this example, where there's a separator.

But I'll do it rather than debate it again.

**Comment by pixelzoom** [comment] 2023-07-02 17:28
This affects all accordion boxes and panels that contain checkboxes, in all 4 screens.

**Comment by pixelzoom** [comment] 2023-07-02 18:02
Done in the above commits, screenshots below.  @arouinfar please review in master. Close if OK.

Notet that for the "Quadratic Terms" accordion box in the first screen, the pointer areas are determined by the width of the accordion box, not the width of the widest checkbox.  This is caused by the fact that the VBox and horizontal separator are stretched to accommodate the title width.  This is the default behavior.  I could program around it, but it would be complicated, more difficult to maintain, and of little/no value.

<img width="231" alt="screenshot_2646" src="https://github.com/phetsims/graphing-quadratics/assets/3046552/5fdc49fe-63ea-4715-944a-63654b216dac">
<img width="268" alt="screenshot_2648" src="https://github.com/phetsims/graphing-quadratics/assets/3046552/b1ae6aca-31c1-461c-8f29-941b9fa2f577">
<img width="256" alt="screenshot_2647" src="https://github.com/phetsims/graphing-quadratics/assets/3046552/65024d24-e654-4a07-bd0c-68e7ac892bdd">
<img width="277" alt="screenshot_2649" src="https://github.com/phetsims/graphing-quadratics/assets/3046552/6b808d2d-b0eb-488b-bc3e-fa183f2d7252">

**Comment by arouinfar** [comment] 2023-07-05 21:39
Thanks @pixelzoom. I didn't realize there were mitigating factors preventing the use of VerticalCheckboxGroup. I appreciate that you took the time to make this change. Looks good in master, closing.

**Closed by arouinfar** 2023-07-05 21:39 UTC
Labels: status:ready-for-review, type:suggestion
