### ISSUE TITLE
CT: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-quadratics#84] opened 2018-10-22 15:19 UTC
```
graphing-quadratics : fuzz : built-phet-io : run
Uncaught TypeError: Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at Function.toStateObject (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952-phet-io/graphing-quadratics/build/phet-io/graphing-quadratics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:979:702208)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952-phet-io/graphing-quadratics/build/phet-io/graphing-quadratics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:979:28057)
    at e.press (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952-phet-io/graphing-quadratics/build/phet-io/graphing-quadratics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:979:707178)
    at e.press (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952-phet-io/graphing-quadratics/build/phet-io/graphing-quadratics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:979:836130)
    at e.tryTouchSnag (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952-phet-io/graphing-quadratics/build/phet-io/graphing-quadratics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:979:836623)
    at e.touchenter (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952-phet-io/graphing-quadratics/build/phet-io/graphing-quadratics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:979:838431)
    at e.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952-phet-io/graphing-quadratics/build/phet-io/graphing-quadratics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:979:1055030)
    at e.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952-phet-io/graphing-quadratics/build/phet-io/graphing-quadratics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:979:1055243)
    at e.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952-phet-io/graphing-quadratics/build/phet-io/graphing-quadratics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:979:1054811)
    at enterEvents (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952-phet-io/graphing-quadratics/build/phet-io/graphing-quadratics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:979:1054457)
id: Bayes Chrome
Approximately 10/21/2018, 10:00:35 PM
graphing-quadratics : phet-io-tests
7 out of 7 tests passed. 0 failed.

Approximately 10/21/2018, 10:00:35 PM
```

**Comment by pixelzoom** [comment] 2018-10-23 02:37
I haven't looked into this yet.  But my first guess is that PhET-iO is attempting to serialize `savedQuadraticProperty`, which is `phetioType: PropertyIO( NullableIO( QuadraticIO ) )`.  The value of this Property is null when there is no saved quadratic.

**Comment by pixelzoom** [comment] 2018-10-23 02:42
>graphing-quadratics : phet-io-tests
7 out of 7 tests passed. 0 failed.

Say what?...  If all tests passed, then why do we have a CT error?

**Comment by pixelzoom** [comment] 2018-10-23 02:47
Reproduced by building `grunt --brand=phet-io`, then running `graphing-quadratics/build/phet-io/graphing-quadratics_all_phet-io.html?fuzz&phetioStandalone`.

**Comment by pixelzoom** [comment] 2018-10-23 02:53
Reproduced with debug version,`graphing-quadratics/build/phet-io/graphing-quadratics_all_phet-io_debug.html?fuzz&phetioStandalone`, but source code is apparently mangled there too.

**Comment by pixelzoom** [comment] 2018-10-23 03:14
Reproduced in requirejs mode with `graphing-quadratics/graphing-quadratics_en.html?fuzz&phetioStandalone&brand=phet-io`. 

Stack trace:

> EventIO.js?bust=1540264140908:45 Uncaught TypeError: Cannot read property 'type' of null
    at Function.toStateObject (EventIO.js?bust=1540264140908:45)
    at Emitter.emit (Emitter.js?bust=1540264140908:168)
    at PointToolDragListener.press (PressListener.js?bust=1540264140908:354)
    at PointToolDragListener.press (DragListener.js?bust=1540264140908:228)
    at PointToolDragListener.tryTouchSnag (DragListener.js?bust=1540264140908:315)
    at PointToolDragListener.touchenter (DragListener.js?bust=1540264140908:552)
    at Input.dispatchToListeners (Input.js?bust=1540264140908:1479)
    at Input.dispatchToTargets (Input.js?bust=1540264140908:1518)
    at Input.dispatchEvent (Input.js?bust=1540264140908:1448)
    at Input.enterEvents (Input.js?bust=1540264140908:1383)

PointToolDragListener is a subclass of DragListener that is added to PointTool node. See PointToolNode line 194.   There's an attempt to serialize a null object is down in PressListener and Emitter. I have no idea how to debug this. @samreid  or @jonathanolson, does this stack trace suggest anything to you?

**Comment by jonathanolson** [comment] 2018-10-23 04:34
Looks like it's the same "trying to serialize an event without a corresponding dom event", that will partially be solved by passing in an old event. I'll handle this.

**Comment by jonathanolson** [comment] 2018-10-24 22:38
This should have been fixed with yesterday's Scenery commit. Can you verify?

**Comment by pixelzoom** [comment] 2018-10-25 01:59
The problem seems to be gone with `graphing-quadratics/graphing-quadratics_en.html?fuzz&phetioStandalone&brand=phet-io`, and I don't see anything in CT.   So closing, thanks.

**Closed by pixelzoom** 2018-10-25 01:59 UTC
Labels: dev:phet-io, priority:2-high, type:automated-testing, type:bug

**Comment by KatieWoe** [comment] 2018-10-25 15:07
Looks clear.  Closing.
