### ISSUE TITLE
p slider is jumpy around 0

### ISSUE THREAD

**Issue by samreid** [phetsims/graphing-quadratics#108] opened 2018-11-14 19:07 UTC
@chrisklus and I were investigating https://github.com/phetsims/graphing-quadratics/issues/52#issuecomment-438747617 and discovered that the p slider is jumpy around 0.  Note that in each case I am moving the mouse smoothly and in one direction.

![slider-knob](https://user-images.githubusercontent.com/679486/48505634-c193c400-e804-11e8-9b14-fe233a62f369.gif)

Note the quadratic itself also jumps:
![jumpy-quadratic-30](https://user-images.githubusercontent.com/679486/48506033-bd1bdb00-e805-11e8-8dbc-0123221f2bcd.gif)

**Comment by pixelzoom** [comment] 2018-11-14 19:41
A similar (but not identical) issue was reported in https://github.com/phetsims/graphing-quadratics/issues/76, and decided to not be a problem.  But in this case, it looks like it's trying to snap while dragging instead of snapping on endDrag.  I'll investigate.

**Comment by pixelzoom** [comment] 2018-11-14 21:14
Oh wait... While snap-to-zero was indeed in the wrong place, this is not a snap-to-zero issue.  This is related to 'skip zero', which is specific to the 'p' slider.   Back to me.

**Comment by pixelzoom** [comment] 2018-11-14 22:47
@samreid Were the GIFs in https://github.com/phetsims/graphing-quadratics/issues/108#issue-380843752 by any chance created on a large monitor?

**Comment by pixelzoom** [comment] 2018-11-14 22:49
@samreid I noticed that the second sentence of https://github.com/phetsims/graphing-quadratics/issues/108#issue-380843752 doesn't end with punctuation and seems like an obvious statement:

> Note that in each case I am moving the mouse

Was there more to this sentence that got lost?

**Comment by samreid** [comment] 2018-11-14 22:50
DELL SP2309W Display 23-inch (2048 x 1152).  Same problem on my bulit-in laptop display 15.4-inch (2880 x 1800)

**Comment by chrisklus** [comment] 2018-11-15 00:34
I'm able to reproduce on my MBP as well. With a trackpad, click near 0 and then roll your finger over 0 and it's jumpy. I'm also seeing the same symptom when doing this with the focus manipulator.

**Comment by pixelzoom** [comment] 2018-11-15 19:40
There was a comparison operator that was inverted in both CoefficientSlider and FocusManipulator, fixed in the above commit (with a bit of additional cleanup in CoefficientSlider). 

@chrisklus could you please verify in master?

**Comment by chrisklus** [comment] 2018-11-15 19:46
Looks great. I tested with the slider and manipulator and am no longer seeing the problem. Ready to close.

**Closed** 2018-11-15 19:52 UTC
