### ISSUE TITLE
Dragging function under pointer tool does not change color of pointer tool

### ISSUE THREAD

**Issue by megan-phet** [phetsims/graphing-quadratics#81] opened 2018-10-19 23:21 UTC
<b>Test Device</b>
- Macbook Pro

<b>Operating System</b>
- macOS 10.13.6

<b>Browser</b>
- Safari
- Firefox
- Does not occur in Chrome

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/211. If a pointer tool is not on top of a function and a function is dragged under the pointer tool, the pointer tool will not change color.

<b>Steps to Reproduce</b>

1. Place pointer tool somewhere.
2. Drag a function underneath the pointer tool. (The pointer tool won't change color.)

<b>Visuals</b>

![kapture 2018-10-19 at 17 10 54](https://user-images.githubusercontent.com/40698031/47247630-19840a00-d3c2-11e8-9517-82659636df1d.gif)
<details>
<summary><b>Troubleshooting Information</b></summary>
Name: ‪Graphing Quadratics‬
URL: https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.38/phet/graphing-quadratics_en_phet.html
Version: 1.0.0-dev.38 2018-10-18 21:15:53 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Safari/605.1.15
Language: en-US
Window: 1105x676
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (2.1 INTEL-10.36.19)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"644353d6","branch":"master"},"brand":{"sha":"1fd6682e","branch":"master"},"chipper":{"sha":"fc5919bb","branch":"master"},"dot":{"sha":"dcccfddd","branch":"master"},"graphing-lines":{"sha":"08b2b43e","branch":"master"},"graphing-quadratics":{"sha":"9b807638","branch":"master"},"joist":{"sha":"b12072c7","branch":"master"},"kite":{"sha":"380cef53","branch":"master"},"phet-core":{"sha":"269c4c8a","branch":"master"},"phet-io":{"sha":"ce77e241","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"534dc595","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"3372700d","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"09507f4d","branch":"master"},"phet-io-wrappers":{"sha":"0a4a3153","branch":"master"},"phetcommon":{"sha":"a2a1aaba","branch":"master"},"query-string-machine":{"sha":"9ae63aab","branch":"master"},"scenery":{"sha":"d7e6c53e","branch":"master"},"scenery-phet":{"sha":"344597e6","branch":"master"},"sherpa":{"sha":"0989d371","branch":"master"},"sun":{"sha":"289fce23","branch":"master"},"tambo":{"sha":"fe63321c","branch":"master"},"tandem":{"sha":"2c4b970a","branch":"master"}}
</details>

**Comment by megan-phet** [comment] 2018-10-20 01:11
Another example.
![kapture 2018-10-19 at 19 08 31](https://user-images.githubusercontent.com/40698031/47249584-88695f00-d3d2-11e8-8bf3-a2441bb4a226.gif)

**Comment by pixelzoom** [comment] 2018-10-21 02:32
Point tools only change color with they are <= 0.01 units from the nearest point on a curve.  When you're dragging a point tool, it will snap to a curve and will therefore satisfy this criteria.  If the point tool is not being dragged and the curve moves, then the point tool will only change color if its location meets the <= 0.01 units criteria.   Snapping the point tool to the curve when the point tool is not being dragged was an option that I explored, but that was problematic - it caused the point tools that were not being dragged to "follow" a curve as it moved.  

@amanda-phet please review and indicate whether you'd like the current behavior to change.

**Comment by pixelzoom** [comment] 2018-10-21 02:33
Changing label from bug to design, because this is currently working as intended.

**Comment by pixelzoom** [comment] 2018-10-21 03:36
We could probably address this by changing 0.01 to some larger number.

**Comment by KatieWoe** [comment] 2018-10-22 16:03
@pixelzoom I think what might have been seen was that the color doesn't always change, even when you are very close, or passing through the spot.  I think this is because the distance between the pointer and the line is larger than it looks, and the line is skipping past that point when being dragged.  I positioned just right the pointer does change color.  So I agree that this a design question.  Here is a video of what I think was showing up.
![orange](https://user-images.githubusercontent.com/41024075/47303657-bb357200-d5e1-11e8-9284-2e16b340c876.gif)

**Comment by amanda-phet** [comment] 2018-10-23 16:16
It seems like if the curve is passing through the point tool, the point tool should flicker orange/black at that moment. In @KatieWoe 's video it seems odd that it doesn't show the point when the parabola passes through the point tool. Is it because the coordinate values are to the nearest tenth, but the criteria for the point tool to change color is that the coordinates are more precise than that (to the nearest 0.01)?

**Comment by KatieWoe** [comment] 2018-10-23 16:24
Another note: the pointer tool is less likely to flash if the slider/curve is moving quickly.

**Comment by pixelzoom** [comment] 2018-10-23 16:38
> It seems like if the curve is passing through the point tool, the point tool should flicker orange/black at that moment.

The parabola is not changing continuously, it is changing discretely.  So there is nothing "passing through" the point tool. The point tool is measuring whatever is within 0.01 units of it after the quadratic(s) have changed.   If you want to track the before/after state of each curve and compute whether any curve passed through a point tool, that is an entirely different (and more complicated) implementation.

**Comment by amanda-phet** [comment] 2018-10-23 17:09
That makes sense. I think we should leave this as-is, since there is no actual bug present, and this did not come up in interviews.

**Comment by pixelzoom** [comment] 2018-10-23 17:15
Reopening. I think it might be worth increasing the tolerance from 0.01 to 0.1, and seeing how that feels.  Would that be OK to try?

**Comment by amanda-phet** [comment] 2018-10-23 17:19
Sure, that's fine with me.

**Comment by KatieWoe** [comment] 2018-10-23 17:20
@pixelzoom I'd be willing to do some comparisons.  See if that's too far and feels off, or if it works.  Either way.  Let me know if you have a new dev build or want it tested on master.

**Comment by KatieWoe** [comment] 2018-10-24 15:10
@pixelzoom @amanda-phet I just took a look and the pointer does indicate when the line is passing through it most of the time.  It doesn't if you'r moving the line very fast, but I doubt there's anything to do about that.  There is the trade-off that @pixelzoom mentioned where the pointer tool may be further from the line when it turns on.  See the image.  I don't think it looks too bad, and the previous version had instances where the pointer tool looked like it was in the center of the line but didn't light up.  I'll look for any instances that look off, but for now this is the furthest I've seen from the center.
![far](https://user-images.githubusercontent.com/41024075/47441070-a2a59300-d76c-11e8-93b3-e1ed04a84f90.PNG)

**Comment by pixelzoom** [comment] 2018-10-24 19:21
The point tool doesn't need to be directly in the center of the line in these situations. As long as the coordinates shown by the point tool are actually on the line, then we're good.  Since the previous of the point tool is 0.1, using `pointToolThreshold: 0.1` should be good.

**Comment by amanda-phet** [comment] 2018-10-25 15:05
I didn't play with other values but 0.1 is looking good to me!

**Comment by amanda-phet** [comment] 2018-10-25 20:20
Kathy agrees that the threshold is working well. Closing.

**Closed by amanda-phet** 2018-10-25 20:20 UTC
Labels: design:general, meeting:design, status:ready-for-review
