### ISSUE TITLE
[FF] Directrix equation changes color with stringTest=long

### ISSUE THREAD

**Issue by rea-laura** [phetsims/graphing-quadratics#123] opened 2018-12-04 17:40 UTC
<b>Test Device</b>

Erdos

<b>Operating System</b>

Mac 10.12.6

<b>Browser</b>

Firefox 63.0.3

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/227:
When testing the "long" string test, the green and purple equation labels sometimes change color.

<b>Steps to Reproduce</b>

1) open sim with "long" string test: https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-rc.1/phet/graphing-quadratics_en_phet.html?stringTest=long
2) go to focus and directrix home screen icon
3) turn on equation labels
4) note that the directrix equation label is purple
5) select and drag the focus point on the graph, observing that the directrix equation label will sometimes change color from purple to green as the focus is moved.

<b>Visuals</b>

Video here:
https://photos.app.goo.gl/ocpsSRXmusTpGb6B6

<b>Details</b>

Not found on windows.
Can also be recreated in other sections of the sim:
- "Explore": "b" line (green) 
- "Standard Form" and "Vertex Form": line of symmetry

**Comment by pixelzoom** [comment] 2018-12-04 17:56
Reproduced on FF 63.0.3 on macOS 10.11.6.  It seems to be specific to FF, since I could not reproduce on Chrome or Safari.  And it's very odd that this only happens with `stringTest=long`.  With other `stringTest` values (double, 'X',...), or the absence of `stringTest`, it does not occur. 

I inspected the source code for `DirectrixNode`.  The equation is initialized here:

```js
      // text of the equation
      const equationText = new RichText( '', {
        font: GQConstants.GRAPHED_EQUATION_FONT,
        fill: GQColors.DIRECTRIX
      } );
```

This private, and the fill is never changed within `DirectrixNode`.   So I'm not sure how the color of the equation could possibly be changing.  

@jonathanolson any ideas?

**Comment by pixelzoom** [comment] 2018-12-04 18:10
I tried `stringTest=1234567890`, with various numbers of digits.  What I'm observing is that the equation is mostly green while dragging the 'p' (leftmost) slider, but then changes color to have more purple in it when the dragging ends.  As the length `stringTest` increases, the equation becomes mostly purple when dragging ends.  

Here are some screenshots, where I'm using the Digital Color Meter application to zoom in on pixels in the equation.

With `stringTest=long`, mostly purple:
![screenshot_913](https://user-images.githubusercontent.com/3046552/49463200-177cdb80-f7b5-11e8-8dd2-5ed0336ac77a.png)

With `stringTest=123456789012`, some purple:
![screenshot_915](https://user-images.githubusercontent.com/3046552/49463214-219eda00-f7b5-11e8-879c-d756dd1701e4.png)

Maybe FF is dithering to purple when the equation gets small enough?

**Comment by pixelzoom** [comment] 2018-12-04 18:16
It's worth noting that this is unlikely to ever occur in practice.  So resolving this is not a prerequisite to publishing 1.0.

**Comment by pixelzoom** [comment] 2018-12-04 22:38
@KatieWoe reported via Slack that she could not reproduce this with Firefox 63.0.3 on macOS 10.14.1.

**Comment by pixelzoom** [comment] 2018-12-04 22:43
Labeling this issue with `priority:deferred` because it's not required for 1.0 publication.  @jonathanolson it's up to you as to when you'd like to investigate.

**Comment by pixelzoom** [comment] 2019-03-25 20:43
Based on https://github.com/phetsims/graphing-quadratics/issues/123#issuecomment-444957237 and the fact that we will never do anything in code to address this... Closing.

**Closed by pixelzoom** 2019-03-25 20:43 UTC
Labels: priority:5-deferred
