### ISSUE TITLE
Point tool stays old color when line is changed beneath it

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-quadratics#196] opened 2023-06-27 19:19 UTC
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/959
The point tool no longer changes color when a line moves out from under it. If it is orange when on a line, and the line is changed, the point tool no longer goes white, it stays orange. This worked properly in published
**Steps to reproduce**
1. Put the point tool on the line
2. Change the line

**Visuals**
![buggq](https://github.com/phetsims/graphing-quadratics/assets/41024075/9ef74a75-a5f4-48be-91e0-70eee48e405c)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Graphing Quadratics‬
URL: https://phet-dev.colorado.edu/html/graphing-quadratics/1.3.0-dev.5/phet/graphing-quadratics_all_phet.html
Version: 1.3.0-dev.5 2023-06-27 15:52:45 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Language: en-US
Window: 1536x714
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment] 2023-06-27 19:22
It then stays the incorrect color even if you drag it around. If the line passes underneath it this happens too.

**Comment by KatieWoe** [comment] 2023-06-27 20:29
When dragging it around, it seems to "stick" to an invisible line

**Comment by pixelzoom** [comment] 2023-07-02 18:19
Reproduced in master.  Not that this does not occur with graphing-lines, because it has a different implementation of point tool.

**Comment by pixelzoom** [comment] 2023-07-06 21:16
The problem was introduced in PointTool.ts by https://github.com/phetsims/graphing-quadratics/commit/2dfd1cbb on 2/18/23.  This was the first phase of TypeScript conversion.

**Comment by pixelzoom** [comment] 2023-07-06 21:21
Fixed in the above commit.

When I converted to TypeScript, this change was made because TypeScript prefers `includes`:

```diff
-         quadratics.indexOf( onQuadratic ) === -1 ||
+         quadratics.includes( quadraticNear ) ||
```

The problem is that I got the logic inverted, and it should have been:

```ts
+         !quadratics.includes( quadraticNear ) ||
```

**Comment by pixelzoom** [comment] 2023-07-06 21:41
Reopening.  Please verify in 1.3.0-rc.1, just in case.

**Closed** 2023-07-10 09:11 UTC
Labels: type:bug, status:ready-for-review
