### ISSUE TITLE
[IE11] Directrix disappears in full screen on Windows 7

### ISSUE THREAD

**Issue by rea-laura** [phetsims/graphing-quadratics#129] opened 2018-12-06 22:26 UTC
<b>Test Device</b>

Bates

<b>Operating System</b>

Windows 7 Enterprise

<b>Browser</b>

Internet explorer 11.0.9600.19180

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/234:
Directrix disappears when point on parabola is moved in full-screen mode

<b>Steps to Reproduce</b>

1) open sim
2) open "focus and directrix" from home page
3) set "p" to its highest value (9.0)
4) turn on "point on parabola"
5) drag point on parabola all the way to the right of the curve
6) using the PhET menu, enter full-screen mode
7) drag the point on the parabola to the left. Directrix will disappear as point passes over it.

<b>Visuals</b>

https://photos.app.goo.gl/Vyvg8Mjt2QPPt26b8

**Comment by KatieWoe** [comment] 2018-12-06 22:36
Note: I was unable to reproduce on a Win 10 IE.

**Comment by pixelzoom** [comment] 2018-12-06 22:59
Bizarre! Nothing here that the sim is doing. @jonathanolson any ideas?

**Comment by pixelzoom** [comment] 2018-12-06 23:02
@ariel-phet Your feelings on whether this blocks 1.0 publication?

**Comment by pixelzoom** [comment] 2018-12-06 23:06
On Slack, @jonathanolson said:
> Weird. Hopefully the full screen part is more a dependence on scale/resolution. I’ll look into it

**Comment by KatieWoe** [comment] 2018-12-06 23:51
Another odd data point: unable to reproduce on Win 8.1.  @lmulhall-phet is currently double checking the other browsers on Win 7.

**Comment by lmulhall-phet** [comment] 2018-12-06 23:53
Double check complete. This bug only occurs on IE.

**Comment by pixelzoom** [comment] 2020-03-12 21:47
According to @KatieWoe via Slack, Win7 + IE is no longer a supported platform.   So closing this issue.

**Closed by pixelzoom** 2020-03-12 21:47 UTC
Labels: priority:5-deferred, type:bug
